name: DeadByDayLightJE2
version: @version@
main: com.github.rain1208.deadbydaylightje2.DeadByDayLightJE2

commands:
  start:
    description: ""
    permission: op
  join:
    description: ""
  leave:
    description: ""
  map:
    description: ""
    permission: op
  autocreate:
    description: ""
    permission: op
  creategame:
    description: ""
    permission: op
  stopgame:
    permission: op
    aliases: ["stopg"]
  oni:
    description: ""
    permission: op